// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Greeting) DeepCopyInto(out *Greeting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopyObject implements runtime.Object.
func (in *Greeting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this Greeting.
func (in *Greeting) DeepCopy() *Greeting {
	if in == nil {
		return nil
	}
	out := new(Greeting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GreetingList) DeepCopyInto(out *GreetingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Greeting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *GreetingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this GreetingList.
func (in *GreetingList) DeepCopy() *GreetingList {
	if in == nil {
		return nil
	}
	out := new(GreetingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GreetingSpec) DeepCopyInto(out *GreetingSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of this GreetingSpec.
func (in *GreetingSpec) DeepCopy() *GreetingSpec {
	if in == nil {
		return nil
	}
	out := new(GreetingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GreetingStatus) DeepCopyInto(out *GreetingStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of this GreetingStatus.
func (in *GreetingStatus) DeepCopy() *GreetingStatus {
	if in == nil {
		return nil
	}
	out := new(GreetingStatus)
	in.DeepCopyInto(out)
	return out
}
